// src/i18n.js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: "en",
    debug: false,
    interpolation: {
      escapeValue: false,
    },
    resources: {
      en: {
        translation: {
          selectLanguage: "Select Language",
          selectLocation: "Select Location",
          noLocationSelected: "No Location Selected", // English

          languages: [
            "English",
            "French",
            "Italian",
            "German",
            "Dutch",
            "Polish",
            "Bulgarian",
            "Russian",
            "Spanish",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          weekdays: [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
          ],
          noDates: "No dates for this month",
          noBookings: "No bookings for this date",
          departure: "Departure",
          seatsAvailable: "Seats Available",
          adult: "Adult",
          child: "Child",
          infant: "Infant",
          bookNow: "Book Now",
        },
      },
      fr: {
        translation: {
          selectLanguage: "Choisir la langue",
          selectLocation: "Choisir un emplacement",
          noLocationSelected: "Aucun emplacement sélectionné", // French
          languages: [
            "Anglais",
            "Français",
            "Italien",
            "Allemand",
            "Néerlandais",
            "Polonais",
            "Bulgare",
            "Russe",
            "Espagnol",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messine",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "Janvier",
            "Février",
            "Mars",
            "Avril",
            "Mai",
            "Juin",
            "Juillet",
            "Août",
            "Septembre",
            "Octobre",
            "Novembre",
            "Décembre",
          ],
          weekdays: [
            "Lundi",
            "Mardi",
            "Mercredi",
            "Jeudi",
            "Vendredi",
            "Samedi",
            "Dimanche",
          ],
          noDates: "Aucune date pour ce mois",
          noBookings: "Aucune réservation pour cette date",
          departure: "Départ",
          seatsAvailable: "Places disponibles",
          adult: "Adulte",
          child: "Enfant",
          infant: "Bébé",
          bookNow: "Réserver",
        },
      },
      it: {
        translation: {
          selectLanguage: "Seleziona la lingua",
          selectLocation: "Seleziona una località",
          noLocationSelected: "Nessuna località selezionata", // Italian
          languages: [
            "Inglese",
            "Francese",
            "Italiano",
            "Tedesco",
            "Olandese",
            "Polacco",
            "Bulgaro",
            "Russo",
            "Spagnolo",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "Gennaio",
            "Febbraio",
            "Marzo",
            "Aprile",
            "Maggio",
            "Giugno",
            "Luglio",
            "Agosto",
            "Settembre",
            "Ottobre",
            "Novembre",
            "Dicembre",
          ],
          weekdays: [
            "Lunedì",
            "Martedì",
            "Mercoledì",
            "Giovedì",
            "Venerdì",
            "Sabato",
            "Domenica",
          ],

          noDates: "Nessuna data per questo mese",
          noBookings: "Nessuna prenotazione per questa data",
          departure: "Partenza",
          seatsAvailable: "Posti disponibili",
          adult: "Adulto",
          child: "Bambino",
          infant: "Neonato",
          bookNow: "Prenota ora",
        },
      },
      de: {
        translation: {
          selectLanguage: "Sprache auswählen",
          selectLocation: "Ort auswählen",
          noLocationSelected: "Kein Ort ausgewählt", // German
          noDates: "Keine Daten für diesen Monat",
          languages: [
            "Englisch",
            "Französisch",
            "Italienisch",
            "Deutsch",
            "Niederländisch",
            "Polnisch",
            "Bulgarisch",
            "Russisch",
            "Spanisch",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "Januar",
            "Februar",
            "März",
            "April",
            "Mai",
            "Juni",
            "Juli",
            "August",
            "September",
            "Oktober",
            "November",
            "Dezember",
          ],
          weekdays: [
            "Montag",
            "Dienstag",
            "Mittwoch",
            "Donnerstag",
            "Freitag",
            "Samstag",
            "Sonntag",
          ],

          noBookings: "Keine Buchungen für dieses Datum",
          departure: "Abfahrt",
          seatsAvailable: "Verfügbare Plätze",
          adult: "Erwachsener",
          child: "Kind",
          infant: "Säugling",
          bookNow: "Jetzt buchen",
        },
      },
      nl: {
        translation: {
          selectLanguage: "Selecteer taal",
          selectLocation: "Selecteer locatie",
          noLocationSelected: "Geen locatie geselecteerd", // Dutch
          languages: [
            "Engels",
            "Frans",
            "Italiaans",
            "Duits",
            "Nederlands",
            "Pools",
            "Bulgaars",
            "Russisch",
            "Spaans",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "Januari",
            "Februari",
            "Maart",
            "April",
            "Mei",
            "Juni",
            "Juli",
            "Augustus",
            "September",
            "Oktober",
            "November",
            "December",
          ],
          weekdays: [
            "Maandag",
            "Dinsdag",
            "Woensdag",
            "Donderdag",
            "Vrijdag",
            "Zaterdag",
            "Zondag",
          ],
          noDates: "Geen datums voor deze maand",
          noBookings: "Geen boekingen voor deze datum",
          departure: "Vertrek",
          seatsAvailable: "Beschikbare plaatsen",
          adult: "Volwassene",
          child: "Kind",
          infant: "Baby",
          bookNow: "Boek nu",
        },
      },
      pl: {
        translation: {
          selectLanguage: "Wybierz język",
          selectLocation: "Wybierz lokalizację",
          noLocationSelected: "Nie wybrano lokalizacji", // Polish
          languages: [
            "Angielski",
            "Francuski",
            "Włoski",
            "Niemiecki",
            "Holenderski",
            "Polski",
            "Bułgarski",
            "Rosyjski",
            "Hiszpański",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "Styczeń",
            "Luty",
            "Marzec",
            "Kwiecień",
            "Maj",
            "Czerwiec",
            "Lipiec",
            "Sierpień",
            "Wrzesień",
            "Październik",
            "Listopad",
            "Grudzień",
          ],
          weekdays: [
            "Poniedziałek",
            "Wtorek",
            "Środa",
            "Czwartek",
            "Piątek",
            "Sobota",
            "Niedziela",
          ],
          noDates: "Brak dat w tym miesiącu",
          noBookings: "Brak rezerwacji na tę datę",
          departure: "Odjazd",
          seatsAvailable: "Dostępne miejsca",
          adult: "Dorosły",
          child: "Dziecko",
          infant: "Niemowlę",
          bookNow: "Zarezerwuj teraz",
        },
      },
      bg: {
        translation: {
          selectLanguage: "Изберете език",
          selectLocation: "Изберете местоположение",
          noLocationSelected: "Не е избрано местоположение", // Bulgarian
          noDates: "Няма дати за този месец",
          languages: [
            "Английски",
            "Френски",
            "Италиански",
            "Немски",
            "Холандски",
            "Полски",
            "Български",
            "Руски",
            "Испански",
          ],
          locations: [
            "Ното",
            "Ликата",
            "Мазара дел Вало",
            "Чефалу",
            "Месина",
            "Каляри",
            "Кастелсардо",
            "Паестум",
          ],
          months: [
            "Януари",
            "Февруари",
            "Март",
            "Април",
            "Май",
            "Юни",
            "Юли",
            "Август",
            "Септември",
            "Октомври",
            "Ноември",
            "Декември",
          ],
          weekdays: [
            "Понеделник",
            "Вторник",
            "Сряда",
            "Четвъртък",
            "Петък",
            "Събота",
            "Неделя",
          ],
          // "noDates": "Няма дати за този месец",
          noBookings: "Няма резервации за тази дата",
          departure: "Отпътуване",
          seatsAvailable: "Налично места",
          adult: "Възрастен",
          child: "Дете",
          infant: "Бебе",
          bookNow: "Резервирай",
        },
      },
      ru: {
        translation: {
          selectLanguage: "Выберите язык",
          selectLocation: "Выберите место",
          noLocationSelected: "Не выбрано место",
          noDates: "Нет дат для этого месяца",
          languages: [
            "Английский",
            "Французский",
            "Итальянский",
            "Немецкий",
            "Голландский",
            "Польский",
            "Болгарский",
            "Русский",
            "Испанский",
          ],
          locations: [
            "Ното",
            "Ликата",
            "Мазара дель Валло",
            "Чефалу",
            "Мессина",
            "Кальяри",
            "Кастельсардо",
            "Паестум",
          ],
          months: [
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь",
          ],
          weekdays: [
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота",
            "Воскресенье",
          ],

          noBookings: "Нет бронирований на эту дату",
          departure: "Отправление",
          seatsAvailable: "Доступные места",
          adult: "Взрослый",
          child: "Ребёнок",
          infant: "Младенец",
          bookNow: "Забронировать",
        },
      },
      es: {
        translation: {
          selectLanguage: "Seleccionar idioma",
          selectLocation: "Seleccionar ubicación",
          noLocationSelected: "No se ha seleccionado ninguna ubicación", // Spanish
          noDates: "No hay fechas para este mes",
          noBookings: "No hay reservas para esta fecha",
          languages: [
            "Inglés",
            "Francés",
            "Italiano",
            "Alemán",
            "Neerlandés",
            "Polaco",
            "Búlgaro",
            "Ruso",
            "Español",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь",
          ],
          weekdays: [
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота",
            "Воскресенье",
          ],

          departure: "Salida",
          seatsAvailable: "Plazas disponibles",
          adult: "Adulto",
          child: "Niño",
          infant: "Infante",
          bookNow: "Reservar ahora",
        },
      },
    },
  });

export default i18n;
