// src/i18n.js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: "en",
    debug: false,
    interpolation: {
      escapeValue: false,
    },
    resources: {
      en: {
        translation: {
          selectLanguage: "Select Language",
          selectLocation: "Select Location",
          languages: [
            "English",
            "French",
            "Italian",
            "German",
            "Dutch",
            "Polish",
            "Bulgarian",
            "Russian",
            "Spanish",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
          months: [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
          ],
          weekdays: [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
          ],
          noDates: "No dates for this month",
          noBookings: "No bookings for this date",
          departure: "Departure",
          seatsAvailable: "Seats Available",
          adult: "Adult",
          child: "Child",
          infant: "Infant",
          bookNow: "Book Now",
        },
      },
      fr: {
        translation: {
          selectLanguage: "Choisir la langue",
          selectLocation: "Choisir un emplacement",
          languages: [
            "Anglais",
            "Français",
            "Italien",
            "Allemand",
            "Néerlandais",
            "Polonais",
            "Bulgare",
            "Russe",
            "Espagnol",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messine",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
        },
      },
      it: {
        translation: {
          selectLanguage: "Seleziona la lingua",
          selectLocation: "Seleziona una località",
          languages: [
            "Inglese",
            "Francese",
            "Italiano",
            "Tedesco",
            "Olandese",
            "Polacco",
            "Bulgaro",
            "Russo",
            "Spagnolo",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
        },
      },
      de: {
        translation: {
          selectLanguage: "Sprache auswählen",
          selectLocation: "Ort auswählen",
          languages: [
            "Englisch",
            "Französisch",
            "Italienisch",
            "Deutsch",
            "Niederländisch",
            "Polnisch",
            "Bulgarisch",
            "Russisch",
            "Spanisch",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
        },
      },
      nl: {
        translation: {
          selectLanguage: "Selecteer taal",
          selectLocation: "Selecteer locatie",
          languages: [
            "Engels",
            "Frans",
            "Italiaans",
            "Duits",
            "Nederlands",
            "Pools",
            "Bulgaars",
            "Russisch",
            "Spaans",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
        },
      },
      pl: {
        translation: {
          selectLanguage: "Wybierz język",
          selectLocation: "Wybierz lokalizację",
          languages: [
            "Angielski",
            "Francuski",
            "Włoski",
            "Niemiecki",
            "Holenderski",
            "Polski",
            "Bułgarski",
            "Rosyjski",
            "Hiszpański",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
        },
      },
      bg: {
        translation: {
          selectLanguage: "Изберете език",
          selectLocation: "Изберете местоположение",
          languages: [
            "Английски",
            "Френски",
            "Италиански",
            "Немски",
            "Холандски",
            "Полски",
            "Български",
            "Руски",
            "Испански",
          ],
          locations: [
            "Ното",
            "Ликата",
            "Мазара дел Вало",
            "Чефалу",
            "Месина",
            "Каляри",
            "Кастелсардо",
            "Паестум",
          ],
        },
      },
      ru: {
        translation: {
          selectLanguage: "Выберите язык",
          selectLocation: "Выберите место",
          languages: [
            "Английский",
            "Французский",
            "Итальянский",
            "Немецкий",
            "Голландский",
            "Польский",
            "Болгарский",
            "Русский",
            "Испанский",
          ],
          locations: [
            "Ното",
            "Ликата",
            "Мазара дель Валло",
            "Чефалу",
            "Мессина",
            "Кальяри",
            "Кастельсардо",
            "Паестум",
          ],
        },
      },
      es: {
        translation: {
          selectLanguage: "Seleccionar idioma",
          selectLocation: "Seleccionar ubicación",
          languages: [
            "Inglés",
            "Francés",
            "Italiano",
            "Alemán",
            "Neerlandés",
            "Polaco",
            "Búlgaro",
            "Ruso",
            "Español",
          ],
          locations: [
            "Noto",
            "Licata",
            "Mazara del Vallo",
            "Cefalù",
            "Messina",
            "Cagliari",
            "Castelsardo",
            "Paestum",
          ],
        },
      },
    },
  });

export default i18n;
